/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"
import { proxy, useSnapshot } from "valtio"
import { HexColorPicker } from "react-colorful"
import Picker from './picker'


const state = proxy({
  current: null,
  items: {
    laces: "#ffffff",
  },
})



export default function Bikejs({ ...props }) {

  const snap = useSnapshot(state)
  // Drei's useGLTF hook sets up draco automatically, that's how it differs from useLoader(GLTFLoader, url)
  // { nodes, materials } are extras that come from useLoader, these do not exist in threejs/GLTFLoader
  // nodes is a named collection of meshes, materials a named collection of materials
  // Animate model
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    group.current.rotation.z = -0.2 - (1 + Math.sin(t / 1.5)) / 20
    group.current.rotation.x = Math.cos(t / 4) / 8
    group.current.rotation.y = Math.sin(t / 4) / 2
    group.current.position.y = (1 + Math.sin(t / 1.5)) / 10
  })

  // Cursor showing current color
  const [hovered, set] = useState(null)

  useEffect(() => {
    const cursor = `<svg width="64" height="64" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path fill="rgba(255, 255, 255, 0.5)" d="M29.5 54C43.031 54 54 43.031 54 29.5S43.031 5 29.5 5 5 15.969 5 29.5 15.969 54 29.5 54z" stroke="#000"/><g filter="url(#filter0_d)"><path d="M29.5 47C39.165 47 47 39.165 47 29.5S39.165 12 29.5 12 12 19.835 12 29.5 19.835 47 29.5 47z" fill="${snap.items[hovered]}"/></g><path d="M2 2l11 2.947L4.947 13 2 2z" fill="#000"/><text fill="#000" style="white-space:pre" font-family="Inter var, sans-serif" font-size="10" letter-spacing="-.01em"><tspan x="35" y="63">${hovered}</tspan></text></g><defs><clipPath id="clip0"><path fill="#fff" d="M0 0h64v64H0z"/></clipPath><filter id="filter0_d" x="6" y="8" width="47" height="47" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="2"/><feGaussianBlur stdDeviation="3"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.15 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow"/><feBlend in="SourceGraphic" in2="effect1_dropShadow" result="shape"/></filter></defs></svg>`
    const auto = `<svg width="64" height="64" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="rgba(255, 255, 255, 0.5)" d="M29.5 54C43.031 54 54 43.031 54 29.5S43.031 5 29.5 5 5 15.969 5 29.5 15.969 54 29.5 54z" stroke="#000"/><path d="M2 2l11 2.947L4.947 13 2 2z" fill="#000"/></svg>`
    if (hovered) {
      document.body.style.cursor = `url('data:image/svg+xml;base64,${btoa(cursor)}'), auto`
      return () => (document.body.style.cursor = `url('data:image/svg+xml;base64,${btoa(auto)}'), auto`)
    }
  }, [hovered])






  const group = useRef()
  const { nodes, materials } = useGLTF('/bike.glb')
  return (
    
    <group ref={group} {...props} dispose={null}
    onPointerOver={(e) => (e.stopPropagation(), set(e.object.material.name))}
    onPointerOut={(e) => e.intersections.length === 0 && set(null)}
    onPointerMissed={() => (state.current = null)}
    onClick={(e) => (e.stopPropagation(), (state.current = e.object.material.name))}
    >
      <mesh
        geometry={nodes['protection-disc_Cylinder002'].geometry}
        rotation={[Math.PI / 2, 0, 0]}
        material={materials.laces} 
        material-color={snap.items.laces}
      />
      <mesh
        geometry={nodes.cylinder_Cylinder001.geometry}
        material={nodes.cylinder_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['stark-temper-kenda-tire_Circle'].geometry}
        material={nodes['stark-temper-kenda-tire_Circle'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['nipple-cap_Cylinder042'].geometry}
        material={nodes['nipple-cap_Cylinder042'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nipple_Cylinder041.geometry}
        material={nodes.nipple_Cylinder041.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke032_Cylinder024.geometry}
        material={nodes.spoke032_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke031_Cylinder024.geometry}
        material={nodes.spoke031_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke030_Cylinder024.geometry}
        material={nodes.spoke030_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke029_Cylinder024.geometry}
        material={nodes.spoke029_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke028_Cylinder024.geometry}
        material={nodes.spoke028_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke027_Cylinder024.geometry}
        material={nodes.spoke027_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke026_Cylinder024.geometry}
        material={nodes.spoke026_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke025_Cylinder024.geometry}
        material={nodes.spoke025_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke024_Cylinder024.geometry}
        material={nodes.spoke024_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke023_Cylinder024.geometry}
        material={nodes.spoke023_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke022_Cylinder024.geometry}
        material={nodes.spoke022_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke021_Cylinder024.geometry}
        material={nodes.spoke021_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke020_Cylinder024.geometry}
        material={nodes.spoke020_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke019_Cylinder024.geometry}
        material={nodes.spoke019_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke018_Cylinder024.geometry}
        material={nodes.spoke018_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke017_Cylinder024.geometry}
        material={nodes.spoke017_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke016_Cylinder024.geometry}
        material={nodes.spoke016_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke015_Cylinder024.geometry}
        material={nodes.spoke015_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke014_Cylinder024.geometry}
        material={nodes.spoke014_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke013_Cylinder024.geometry}
        material={nodes.spoke013_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke012_Cylinder024.geometry}
        material={nodes.spoke012_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke011_Cylinder024.geometry}
        material={nodes.spoke011_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke010_Cylinder024.geometry}
        material={nodes.spoke010_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke009_Cylinder024.geometry}
        material={nodes.spoke009_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke008_Cylinder024.geometry}
        material={nodes.spoke008_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke007_Cylinder024.geometry}
        material={nodes.spoke007_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke006_Cylinder024.geometry}
        material={nodes.spoke006_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke005_Cylinder024.geometry}
        material={nodes.spoke005_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke004_Cylinder024.geometry}
        material={nodes.spoke004_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke003_Cylinder024.geometry}
        material={nodes.spoke003_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke002_Cylinder024.geometry}
        material={nodes.spoke002_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke001_Cylinder024.geometry}
        material={nodes.spoke001_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['rear-hub_Cylinder003'].geometry}
        material={materials['rear-hub-quando']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['stark-temper-rim-black_Plane015'].geometry}
        material={nodes['stark-temper-rim-black_Plane015'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['stark-temper-rim_Plane007'].geometry}
        material={nodes['stark-temper-rim_Plane007'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.cylinder002_Cylinder000.geometry}
        material={nodes.cylinder002_Cylinder000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.cylinder001_Cylinder000.geometry}
        material={nodes.cylinder001_Cylinder000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['stark-temper-kenda-tire001_Circle'].geometry}
        material={nodes['stark-temper-kenda-tire001_Circle'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nipple001_Cylinder041.geometry}
        material={nodes.nipple001_Cylinder041.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['nipple-cap001_Cylinder042'].geometry}
        material={nodes['nipple-cap001_Cylinder042'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke064_Cylinder024.geometry}
        material={nodes.spoke064_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke063_Cylinder024.geometry}
        material={nodes.spoke063_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke062_Cylinder024.geometry}
        material={nodes.spoke062_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke061_Cylinder024.geometry}
        material={nodes.spoke061_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke060_Cylinder024.geometry}
        material={nodes.spoke060_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke059_Cylinder024.geometry}
        material={nodes.spoke059_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke058_Cylinder024.geometry}
        material={nodes.spoke058_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke057_Cylinder024.geometry}
        material={nodes.spoke057_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke056_Cylinder024.geometry}
        material={nodes.spoke056_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke055_Cylinder024.geometry}
        material={nodes.spoke055_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke054_Cylinder024.geometry}
        material={nodes.spoke054_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke053_Cylinder024.geometry}
        material={nodes.spoke053_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke052_Cylinder024.geometry}
        material={nodes.spoke052_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke051_Cylinder024.geometry}
        material={nodes.spoke051_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke050_Cylinder024.geometry}
        material={nodes.spoke050_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke049_Cylinder024.geometry}
        material={nodes.spoke049_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke048_Cylinder024.geometry}
        material={nodes.spoke048_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke047_Cylinder024.geometry}
        material={nodes.spoke047_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke046_Cylinder024.geometry}
        material={nodes.spoke046_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke045_Cylinder024.geometry}
        material={nodes.spoke045_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke044_Cylinder024.geometry}
        material={nodes.spoke044_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke043_Cylinder024.geometry}
        material={nodes.spoke043_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke042_Cylinder024.geometry}
        material={nodes.spoke042_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke041_Cylinder024.geometry}
        material={nodes.spoke041_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke040_Cylinder024.geometry}
        material={nodes.spoke040_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke039_Cylinder024.geometry}
        material={nodes.spoke039_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke038_Cylinder024.geometry}
        material={nodes.spoke038_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke037_Cylinder024.geometry}
        material={nodes.spoke037_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke036_Cylinder024.geometry}
        material={nodes.spoke036_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke035_Cylinder024.geometry}
        material={nodes.spoke035_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke034_Cylinder024.geometry}
        material={nodes.spoke034_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.spoke033_Cylinder024.geometry}
        material={nodes.spoke033_Cylinder024.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['front-hub_Cylinder004'].geometry}
        material={materials['front-hub-quando']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['stark-temper-rim-front_Plane007'].geometry}
        material={nodes['stark-temper-rim-front_Plane007'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube001_Cube.geometry}
        material={nodes.Cube001_Cube.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['stark-temper-rim-black-front_Plane015'].geometry}
        material={nodes['stark-temper-rim-black-front_Plane015'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle009.geometry}
        material={materials['reflector-chrome']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle011_Circle007.geometry}
        material={nodes.Circle011_Circle007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['reflector-transparent_Circle005'].geometry}
        material={materials['red-plastic']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['seat-tube004_Cylinder009'].geometry}
        material={nodes['seat-tube004_Cylinder009'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle009.geometry} material={nodes.Circle009.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle009000.geometry}
        material={nodes.Circle009000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001000.geometry}
        material={nodes.Plane001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Grid.geometry} material={nodes.Grid.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle007_Circle002.geometry}
        material={nodes.Circle007_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_Circle001.geometry}
        material={nodes.Circle006_Circle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_Circle.geometry}
        material={nodes.Circle005_Circle.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube003_Cylinder005'].geometry}
        material={nodes['seat-tube003_Cylinder005'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube002_Cylinder008'].geometry}
        material={nodes['seat-tube002_Cylinder008'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_Cylinder007.geometry}
        material={nodes.Cylinder002_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Circle003.geometry}
        material={nodes.Circle004_Circle003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001_Cylinder006.geometry}
        material={nodes.Cylinder001_Cylinder006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['frame-tubes002_Cylinder004'].geometry}
        material={nodes['frame-tubes002_Cylinder004'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane002_Plane003.geometry}
        material={nodes.Plane002_Plane003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001001.geometry}
        material={nodes.Plane001001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials['saddle-mixed']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder_Cylinder002.geometry}
        material={materials['aluminium-0.2']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003_Mesh002.geometry}
        material={nodes.Circle003_Mesh002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_Mesh001.geometry}
        material={nodes.Circle002_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001_Mesh.geometry}
        material={nodes.Circle001_Mesh.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle_Mesh.geometry}
        material={nodes.Circle_Mesh.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube001_Cylinder001'].geometry}
        material={materials['black-plastic-0.2']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube_Cylinder'].geometry}
        material={materials['seat-tube-mixed']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release002_Cylinder004'].geometry}
        material={nodes['quick-release002_Cylinder004'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release001_Cylinder002'].geometry}
        material={nodes['quick-release001_Cylinder002'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release003_Circle003'].geometry}
        material={nodes['quick-release003_Circle003'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release_Circle004'].geometry}
        material={materials['black-paint-0.05_logo-quando.png']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle020.geometry}
        material={materials['cartrige-system-top']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['shifter-right_Plane006'].geometry}
        material={nodes['shifter-right_Plane006'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane016_Plane_1.geometry} material={nodes.Plane016_Plane_1.material} />
        <mesh geometry={nodes.Plane016_Plane_2.geometry} material={nodes.Plane016_Plane_2.material} />
      </group>
      <mesh
        geometry={nodes.Plane015_Plane001.geometry}
        material={nodes.Plane015_Plane001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane014_Plane002.geometry}
        material={nodes.Plane014_Plane002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane013_Plane004.geometry}
        material={nodes.Plane013_Plane004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle009_Circle002.geometry}
        material={nodes.Circle009_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle008_Circle003.geometry}
        material={nodes.Circle008_Circle003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane012_Plane009.geometry}
        material={nodes.Plane012_Plane009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder018_Cylinder002.geometry}
        material={nodes.Cylinder018_Cylinder002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane011_Plane010.geometry}
        material={nodes.Plane011_Plane010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube001_Cube000.geometry}
        material={nodes.Cube001_Cube000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane010_Plane011.geometry}
        material={nodes.Plane010_Plane011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle007_Circle010.geometry}
        material={nodes.Circle007_Circle010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane005_Plane012.geometry}
        material={nodes.Plane005_Plane012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder017_Cylinder007.geometry}
        material={nodes.Cylinder017_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder016_Cylinder007.geometry}
        material={nodes.Cylinder016_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder015_Cylinder007.geometry}
        material={nodes.Cylinder015_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder013_Cylinder010.geometry}
        material={nodes.Cylinder013_Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder012_Cylinder011.geometry}
        material={nodes.Cylinder012_Cylinder011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_Circle012.geometry}
        material={nodes.Circle006_Circle012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_Circle013.geometry}
        material={nodes.Circle005_Circle013.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane023_Plane005.geometry}
        material={nodes.Plane023_Plane005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane020_Mesh001.geometry}
        material={nodes.Plane020_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane019_Mesh002.geometry}
        material={nodes.Plane019_Mesh002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane018_Mesh002.geometry}
        material={nodes.Plane018_Mesh002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane017_Mesh001.geometry}
        material={nodes.Plane017_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['shifter-left_Plane006'].geometry}
        material={nodes['shifter-left_Plane006'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane022_Plane005.geometry}
        material={nodes.Plane022_Plane005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003_Circle013.geometry}
        material={nodes.Circle003_Circle013.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_Circle012.geometry}
        material={nodes.Circle002_Circle012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008_Cylinder007.geometry}
        material={nodes.Cylinder008_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006_Cylinder007.geometry}
        material={nodes.Cylinder006_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane009_Plane012.geometry}
        material={nodes.Plane009_Plane012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Circle010.geometry}
        material={nodes.Circle004_Circle010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane008_Plane011.geometry}
        material={nodes.Plane008_Plane011.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube000.geometry} material={nodes.Cube000.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Plane007_Plane010.geometry}
        material={nodes.Plane007_Plane010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder002.geometry}
        material={nodes.Cylinder005_Cylinder002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane006_Plane009.geometry}
        material={nodes.Plane006_Plane009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001_Circle003.geometry}
        material={nodes.Circle001_Circle003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle_Circle002.geometry}
        material={nodes.Circle_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Plane003_Plane002.geometry}
        material={nodes.Plane003_Plane002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane002_Plane001.geometry}
        material={nodes.Plane002_Plane001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane001_Plane_1.geometry} material={nodes.Plane001_Plane_1.material} />
        <mesh geometry={nodes.Plane001_Plane_2.geometry} material={nodes.Plane001_Plane_2.material} />
      </group>
      <mesh geometry={nodes.Plane_Mesh.geometry} material={materials.handlebar} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder004_Cylinder001.geometry}
        material={nodes.Cylinder004_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003_Cylinder001.geometry}
        material={nodes.Cylinder003_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_Cylinder001.geometry}
        material={nodes.Cylinder002_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.stem} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['seat-tube004_Cylinder009000'].geometry}
        material={nodes['seat-tube004_Cylinder009000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['reflector-transparent_Circle005000'].geometry}
        material={nodes['reflector-transparent_Circle005000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle011_Circle007000.geometry}
        material={nodes.Circle011_Circle007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Sphere000.geometry} material={nodes.Sphere000.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle008_Circle003000.geometry}
        material={nodes.Circle008_Circle003000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Circle003000.geometry}
        material={nodes.Circle004_Circle003000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle014_Circle002.geometry}
        material={nodes.Circle014_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle013_Circle002.geometry}
        material={nodes.Circle013_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle002.geometry}
        material={nodes.Circle012_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle011_Circle002.geometry}
        material={nodes.Circle011_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane000.geometry} material={nodes.Plane000.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle007_Circle008.geometry}
        material={nodes.Circle007_Circle008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_Circle007.geometry}
        material={nodes.Circle006_Circle007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_Circle006.geometry}
        material={materials['cartridge-system-bottom']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003_Circle001.geometry}
        material={nodes.Circle003_Circle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011_Cylinder005.geometry}
        material={nodes.Cylinder011_Cylinder005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder021_Cylinder008.geometry}
        material={nodes.Cylinder021_Cylinder008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release002_Cylinder004000'].geometry}
        material={nodes['quick-release002_Cylinder004000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release001_Cylinder002000'].geometry}
        material={nodes['quick-release001_Cylinder002000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release003_Circle003000'].geometry}
        material={nodes['quick-release003_Circle003000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release_Circle001'].geometry}
        material={nodes['quick-release_Circle001'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010_Mesh002.geometry}
        material={nodes.Cylinder010_Mesh002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder009_Mesh001.geometry}
        material={nodes.Cylinder009_Mesh001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_Circle005.geometry}
        material={nodes.Circle002_Circle005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001_Circle004.geometry}
        material={nodes.Circle001_Circle004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007_Mesh.geometry}
        material={nodes.Cylinder007_Mesh.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder001.geometry}
        material={nodes.Cylinder005_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006_Mesh.geometry}
        material={nodes.Cylinder006_Mesh.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004_Cylinder007.geometry}
        material={nodes.Cylinder004_Cylinder007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003_Cylinder002.geometry}
        material={nodes.Cylinder003_Cylinder002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['frame-tubes003_Cylinder006'].geometry}
        material={materials['fork-top-arc']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001000.geometry}
        material={nodes.Cylinder001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder000.geometry}
        material={nodes.Cylinder000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle030_Circle007_1.geometry} material={materials['shimano-mf-tz21-w-label']} />
        <mesh geometry={nodes.Circle030_Circle007_2.geometry} material={nodes.Circle030_Circle007_2.material} />
        <mesh geometry={nodes.Circle030_Circle007_3.geometry} material={materials.sprockets} />
      </group>
      <mesh
        geometry={nodes.Circle016_Circle022.geometry}
        material={nodes.Circle016_Circle022.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle034_Circle016_1.geometry} material={nodes.Circle034_Circle016_1.material} />
        <mesh geometry={nodes.Circle034_Circle016_2.geometry} material={nodes.Circle034_Circle016_2.material} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane008_Plane007_1.geometry} material={nodes.Plane008_Plane007_1.material} />
        <mesh geometry={nodes.Plane008_Plane007_2.geometry} material={nodes.Plane008_Plane007_2.material} />
      </group>
      <mesh
        geometry={nodes.Circle031_Circle038.geometry}
        material={nodes.Circle031_Circle038.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle032_Circle013.geometry}
        material={nodes.Circle032_Circle013.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle033_Circle021.geometry}
        material={nodes.Circle033_Circle021.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle027_Circle026.geometry}
        material={nodes.Circle027_Circle026.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle026_Circle025.geometry}
        material={nodes.Circle026_Circle025.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle024_Circle023.geometry}
        material={nodes.Circle024_Circle023.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle022_Circle021.geometry}
        material={nodes.Circle022_Circle021.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle023_Circle016_1.geometry} material={nodes.Circle023_Circle016_1.material} />
        <mesh geometry={nodes.Circle023_Circle016_2.geometry} material={nodes.Circle023_Circle016_2.material} />
      </group>
      <mesh
        geometry={nodes.Circle029_Circle038.geometry}
        material={nodes.Circle029_Circle038.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane007_1.geometry} material={nodes.Plane007_1.material} />
        <mesh geometry={nodes.Plane007_2.geometry} material={nodes.Plane007_2.material} />
      </group>
      <mesh
        geometry={nodes.Circle021_Circle015.geometry}
        material={nodes.Circle021_Circle015.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle020_Circle014.geometry}
        material={nodes.Circle020_Circle014.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle019_Circle014.geometry}
        material={nodes.Circle019_Circle014.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube002_Cylinder037'].geometry}
        material={nodes['seat-tube002_Cylinder037'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder037_Cylinder036.geometry}
        material={materials.spring}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder036_Cylinder035.geometry}
        material={nodes.Cylinder036_Cylinder035.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle018_Circle012.geometry}
        material={nodes.Circle018_Circle012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle017_Circle008.geometry}
        material={nodes.Circle017_Circle008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder029_Cylinder032.geometry}
        material={nodes.Cylinder029_Cylinder032.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder032_Cylinder030.geometry}
        material={nodes.Cylinder032_Cylinder030.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder031_Cylinder029.geometry}
        material={nodes.Cylinder031_Cylinder029.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle014_Circle003_1.geometry} material={materials['front-derailleur-w-label']} />
        <mesh
          geometry={nodes.Circle014_Circle003_2.geometry}
          material={materials['front-derailleur-base_shimano-sis-42t-mask.png']}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder030_Cylinder025.geometry}
        material={nodes.Cylinder030_Cylinder025.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder028_Cylinder004.geometry}
        material={materials['metal-0.2-darker']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder027_Cylinder.geometry}
        material={nodes.Cylinder027_Cylinder.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes['seat-tube000_Cylinder000_1'].geometry}
          material={materials['front-derailleur-base_stark-temper-frame-masks-for-uv-mapping.p']}
        />
        <mesh
          geometry={nodes['seat-tube000_Cylinder000_2'].geometry}
          material={nodes['seat-tube000_Cylinder000_2'].material}
        />
      </group>
      <mesh
        geometry={nodes['seat-tube001_Cylinder008'].geometry}
        material={materials['pins-matte_stark-temper-frame-masks-for-uv-mapping.png']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder008_Cylinder007000.geometry}
        material={nodes.Cylinder008_Cylinder007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007000.geometry}
        material={nodes.Cylinder007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006_Cylinder007000.geometry}
        material={nodes.Cylinder006_Cylinder007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder006.geometry}
        material={nodes.Cylinder005_Cylinder006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004_Cylinder005.geometry}
        material={nodes.Cylinder004_Cylinder005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_Cylinder003.geometry}
        material={nodes.Cylinder002_Cylinder003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001_Cylinder002.geometry}
        material={nodes.Cylinder001_Cylinder002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_Cylinder002000.geometry}
        material={nodes.Cylinder_Cylinder002000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane004000.geometry}
        material={nodes.Plane004000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Plane001002.geometry}
        material={nodes.Plane001002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane008_1.geometry} material={nodes.Plane008_1.material} />
        <mesh geometry={nodes.Plane008_2.geometry} material={materials['shimano-altus-label']} />
      </group>
      <mesh geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle000.geometry} material={nodes.Circle000.material} rotation={[Math.PI / 2, 0, 0]} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['chain-inner-link_Circle020_1'].geometry} material={materials['chain-inner-links']} />
        <mesh
          geometry={nodes['chain-inner-link_Circle020_2'].geometry}
          material={nodes['chain-inner-link_Circle020_2'].material}
        />
        <mesh
          geometry={nodes['chain-inner-link_Circle020_3'].geometry}
          material={nodes['chain-inner-link_Circle020_3'].material}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['chain-outer-link_Circle018_1'].geometry} material={materials['chain-outer-links']} />
        <mesh
          geometry={nodes['chain-outer-link_Circle018_2'].geometry}
          material={nodes['chain-outer-link_Circle018_2'].material}
        />
        <mesh
          geometry={nodes['chain-outer-link_Circle018_3'].geometry}
          material={nodes['chain-outer-link_Circle018_3'].material}
        />
      </group>
      <mesh
        geometry={nodes.collar_Cylinder001.geometry}
        material={nodes.collar_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_Cylinder001000.geometry}
        material={nodes.Cylinder002_Cylinder001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle019_Circle013.geometry}
        material={nodes.Circle019_Circle013.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle018_Circle012000.geometry}
        material={nodes.Circle018_Circle012000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle011.geometry} material={nodes.Circle011.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle021_Circle.geometry}
        material={nodes.Circle021_Circle.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle020_Circle006.geometry}
        material={nodes.Circle020_Circle006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle017_Circle004.geometry}
        material={nodes.Circle017_Circle004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle016_Circle005.geometry}
        material={nodes.Circle016_Circle005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Torus000_Torus001.geometry}
        material={nodes.Torus000_Torus001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001_Cylinder.geometry}
        material={nodes.Cylinder001_Cylinder.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle015_Circle007.geometry}
        material={nodes.Circle015_Circle007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle014_Circle008.geometry}
        material={nodes.Circle014_Circle008.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle013_Circle007.geometry}
        material={nodes.Circle013_Circle007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle009000.geometry}
        material={nodes.Circle012_Circle009000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001_Plane000.geometry}
        material={nodes.Plane001_Plane000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001000.geometry}
        material={nodes.Circle001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle010_Circle009.geometry}
        material={nodes.Circle010_Circle009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle009_Circle007.geometry}
        material={nodes.Circle009_Circle007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Circle007.geometry} material={nodes.Circle007.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Torus001.geometry} material={nodes.Torus001.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle006_Circle005.geometry}
        material={nodes.Circle006_Circle005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_Circle004.geometry}
        material={nodes.Circle005_Circle004.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Circle002.geometry}
        material={nodes.Circle004_Circle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle002_Circle006.geometry}
        material={nodes.Circle002_Circle006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle010.geometry} material={nodes.Circle010.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cylinder000_Cylinder001.geometry}
        material={nodes.Cylinder000_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['top-tube_Cylinder014'].geometry}
        material={nodes['top-tube_Cylinder014'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['down-tube_Cylinder013'].geometry}
        material={nodes['down-tube_Cylinder013'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['seat-tube_Cylinder011'].geometry}
        material={nodes['seat-tube_Cylinder011'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes['s-logo_Grid'].geometry} material={materials['s-logo']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['quick-release002_Cylinder004001'].geometry}
        material={nodes['quick-release002_Cylinder004001'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release001_Cylinder002001'].geometry}
        material={nodes['quick-release001_Cylinder002001'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release003_Circle003001'].geometry}
        material={nodes['quick-release003_Circle003001'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['quick-release_Circle001000'].geometry}
        material={nodes['quick-release_Circle001000'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder022_Cylinder012.geometry}
        material={nodes.Cylinder022_Cylinder012.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder021_Cylinder008000.geometry}
        material={nodes.Cylinder021_Cylinder008000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nut004_Cylinder010.geometry}
        material={nodes.nut004_Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder020_Cylinder009.geometry}
        material={nodes.Cylinder020_Cylinder009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder019_Cylinder009.geometry}
        material={nodes.Cylinder019_Cylinder009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nut003_Cylinder010.geometry}
        material={nodes.nut003_Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nut002_Cylinder010.geometry}
        material={nodes.nut002_Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder018_Cylinder009.geometry}
        material={nodes.Cylinder018_Cylinder009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder017_Cylinder009.geometry}
        material={nodes.Cylinder017_Cylinder009.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.nut001_Cylinder010.geometry}
        material={nodes.nut001_Cylinder010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder015_Cylinder001.geometry}
        material={nodes.Cylinder015_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder014_Cylinder001.geometry}
        material={nodes.Cylinder014_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder013_Cylinder001.geometry}
        material={nodes.Cylinder013_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder012_Cylinder001.geometry}
        material={nodes.Cylinder012_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011_Cylinder001.geometry}
        material={nodes.Cylinder011_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010_Cylinder001.geometry}
        material={nodes.Cylinder010_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder009_Cylinder001.geometry}
        material={nodes.Cylinder009_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Cube001_Cube002.geometry}
        material={nodes.Cube001_Cube002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes['welding-seams-symmetric001_Cylinder007'].geometry}
        material={nodes['welding-seams-symmetric001_Cylinder007'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008_Cylinder001.geometry}
        material={nodes.Cylinder008_Cylinder001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007_Cylinder028.geometry}
        material={nodes.Cylinder007_Cylinder028.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder006_Cylinder027.geometry}
        material={nodes.Cylinder006_Cylinder027.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['welding-seams_Mesh007'].geometry}
        material={nodes['welding-seams_Mesh007'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['welding-seams-symmetric_Cylinder007'].geometry}
        material={nodes['welding-seams-symmetric_Cylinder007'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005_Cylinder006000.geometry}
        material={nodes.Cylinder005_Cylinder006000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Mesh.geometry}
        material={nodes.Circle004_Mesh.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003_Mesh003.geometry}
        material={nodes.Circle003_Mesh003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_Circle033.geometry}
        material={nodes.Circle002_Circle033.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle028.geometry}
        material={nodes.Circle012_Circle028.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle010_Circle027.geometry}
        material={nodes.Circle010_Circle027.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle015_Mesh006.geometry}
        material={nodes.Circle015_Mesh006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_Circle010.geometry}
        material={nodes.Circle006_Circle010.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder004_Cylinder.geometry}
        material={nodes.Cylinder004_Cylinder.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001_Mesh003.geometry}
        material={nodes.Circle001_Mesh003.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle_Mesh000.geometry}
        material={nodes.Circle_Mesh000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['front-tube_Cylinder003'].geometry}
        material={nodes['front-tube_Cylinder003'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['frame-tubes001_Cylinder005'].geometry}
        material={nodes['frame-tubes001_Cylinder005'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002_Cylinder001001.geometry}
        material={nodes.Cylinder002_Cylinder001001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle019_Circle013000.geometry}
        material={nodes.Circle019_Circle013000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle018_Circle012001.geometry}
        material={nodes.Circle018_Circle012001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle011000.geometry}
        material={nodes.Circle011000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle021_Circle000.geometry}
        material={nodes.Circle021_Circle000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle020_Circle006000.geometry}
        material={nodes.Circle020_Circle006000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle017_Circle004000.geometry}
        material={nodes.Circle017_Circle004000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle016_Circle005000.geometry}
        material={nodes.Circle016_Circle005000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Torus000_Torus001000.geometry}
        material={nodes.Torus000_Torus001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001_Cylinder000.geometry}
        material={nodes.Cylinder001_Cylinder000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle015_Circle007000.geometry}
        material={nodes.Circle015_Circle007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle014_Circle008000.geometry}
        material={nodes.Circle014_Circle008000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle013_Circle007000.geometry}
        material={nodes.Circle013_Circle007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_Circle009001.geometry}
        material={nodes.Circle012_Circle009001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001_Plane001.geometry}
        material={nodes.Plane001_Plane001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001001.geometry}
        material={nodes.Circle001001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle010_Circle009000.geometry}
        material={nodes.Circle010_Circle009000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle009_Circle007000.geometry}
        material={nodes.Circle009_Circle007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle008000.geometry}
        material={nodes.Circle008000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle007000.geometry}
        material={nodes.Circle007000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Torus001000.geometry}
        material={nodes.Torus001000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_Circle005000.geometry}
        material={nodes.Circle006_Circle005000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_Circle004000.geometry}
        material={nodes.Circle005_Circle004000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_Circle002000.geometry}
        material={nodes.Circle004_Circle002000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003000.geometry}
        material={nodes.Circle003000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_Circle006000.geometry}
        material={nodes.Circle002_Circle006000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle012.geometry} material={nodes.Circle012.material} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.Circle014_CUCircle001.geometry}
        material={nodes.Circle014_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle013_CUCircle001.geometry}
        material={nodes.Circle013_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle012_CUCircle001.geometry}
        material={nodes.Circle012_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle011_CUCircle001.geometry}
        material={nodes.Circle011_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle010_CUCircle001.geometry}
        material={nodes.Circle010_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle009_CUCircle001.geometry}
        material={nodes.Circle009_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle008_CUCircle001.geometry}
        material={nodes.Circle008_CUCircle001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle007_CUCircle000.geometry}
        material={nodes.Circle007_CUCircle000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle005_CUCircle002.geometry}
        material={nodes.Circle005_CUCircle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle004_CUCircle002.geometry}
        material={nodes.Circle004_CUCircle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle003_CUCircle002.geometry}
        material={nodes.Circle003_CUCircle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['rear-brake-connector-cross-section_CUrear-brake-connector-cross'].geometry}
        material={nodes['rear-brake-connector-cross-section_CUrear-brake-connector-cross'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['front-brake-connector-cross-section_CUfront-brake-connector-cro'].geometry}
        material={nodes['front-brake-connector-cross-section_CUfront-brake-connector-cro'].material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006_CUCircle000.geometry}
        material={nodes.Circle006_CUCircle000.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002_CUCircle002.geometry}
        material={nodes.Circle002_CUCircle002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.BezierCurve010.geometry}
        material={materials['sleeve-metal-arcs']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.BezierCurve007.geometry}
        material={nodes.BezierCurve007.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.BezierCurve006.geometry}
        material={nodes.BezierCurve006.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle001002.geometry}
        material={nodes.Circle001002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Circle013.geometry} material={nodes.Circle013.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}


useGLTF.preload('/bike.glb')
